---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip
  # ssh_known_hosts:
  #   - localhost

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-galaxy install -r requirements.txt
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
