---
language: python
python: "2.7"

sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip
  # ssh_known_hosts:
  #   - localhost

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  - pwd
  - ansible-galaxy install --roles-path . -r requirements.yml
  - ls -la
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
